name: pf
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_email_sender: ^6.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.4.0
  lottie: ^2.5.0
  shimmer: ^2.0.0
  universal_html: ^2.0.9
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tek.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
